services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: sh -c "composer install && php artisan serve --host=0.0.0.0 --port=8000"
    environment:
      DB_CONNECTION: sqlsrv
      DB_HOST: db
      DB_PORT: 1433
      DB_DATABASE: laravel
      DB_USERNAME: sa
      DB_PASSWORD: MyS3curePass!

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver_db
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "MyS3curePass!"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
